import fs from 'node:fs';
import path from 'node:path';

const root=process.cwd();
const dist=path.join(root,'dist');
function walk(dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(dir,e.name)):[path.join(dir,e.name)]);}
function pageLocale(rel){if(rel.startsWith('he/'))return'he';if(rel.startsWith('hu/'))return'hu';if(rel.startsWith('pt/'))return'pt';return'en';}
function routeFromRel(rel){return'/'+rel.replace(/index\.html$/,'').replace(/\\/g,'/');}
function budapestSuffix(rel){return rel.replace(/^(he\/|hu\/)?budapest\//,'').replace(/index\.html$/,'').replace(/\/$/,'');}
function budapestPath(locale,suffix=''){const prefix=locale==='he'?'/he/budapest/':locale==='hu'?'/hu/budapest/':'/budapest/';return prefix+(suffix?`${suffix}/`:'');}
function bookingHref(locale,suffix=''){const home=budapestPath(locale);if(suffix==='tours/buda-castle-ezraider-tour')return`${home}?experience=buda-highlights#booking`;if(suffix==='tours/margaret-island-ezraider-tour')return`${home}?experience=margaret-island#booking`;if(suffix==='private-tours')return`${home}?mode=private#booking`;return`${home}#booking`;}
function budapestLabels(locale){
 if(locale==='he')return{nav:'ניווט ראשי',buda:'סיור בודה',margaret:'אי מרגיט',extended:'בודה + מרגיט',private:'סיור פרטי',portugal:'פורטוגל',availability:'בדיקת זמינות',language:'שפה',intro:'סיורי EZRaider מודרכים בבודפשט.',tours:'סיורים',budaFull:'בודה ומצודת הדייגים',margaretFull:'אי מרגיט',extendedFull:'הסיור הארוך',privateFull:'סיור פרטי',kids:'בודפשט עם ילדים',plan:'תכנון',first:'יום ראשון בבודפשט',stay:'איפה לישון',groups:'קבוצות',corporate:'אירועי חברה',service:'שירות',manage:'ניהול הזמנה'};
 if(locale==='hu')return{nav:'Fő navigáció',buda:'Budavári túra',margaret:'Margitsziget',extended:'Buda + Margitsziget',private:'Privát túrák',portugal:'Portugália',availability:'Szabad időpontok',language:'Nyelv',intro:'Vezetett EZRaider túrák Budapesten.',tours:'Túrák',budaFull:'Budai Vár és Halászbástya',margaretFull:'Margitsziget',extendedFull:'Hosszabb túra',privateFull:'Privát túrák',kids:'Budapest gyerekekkel',plan:'Tervezés',first:'Első nap Budapesten',stay:'Hol érdemes megszállni',groups:'Csoportok',corporate:'Céges események',service:'Ügyintézés',manage:'Foglalás kezelése'};
 return{nav:'Primary navigation',buda:'Buda Castle Tour',margaret:'Margaret Island',extended:'Extended Buda + Margaret',private:'Private Tours',portugal:'Portugal',availability:'Check availability',language:'Language',intro:'Guided EZRaider tours in Budapest.',tours:'Tours',budaFull:'Buda Castle & Fisherman’s Bastion',margaretFull:'Margaret Island',extendedFull:'Extended Buda + Margaret',privateFull:'Private Tours',kids:'Budapest with Kids',plan:'Plan',first:'First Day in Budapest',stay:'Where to Stay',groups:'Groups',corporate:'Corporate Events',service:'Service',manage:'Manage Booking'};
}
function budapestHeader(locale,suffix){const l=budapestLabels(locale),home=budapestPath(locale),equivalent={en:budapestPath('en',suffix),hu:budapestPath('hu',suffix),he:budapestPath('he',suffix)},ptLink=locale==='he'?'/he/portugal/':'/portugal/',active=c=>c===locale?' active':'';return`<header><div class="wrap nav"><a class="brand" href="${home}">VOY<span>PRO</span></a><nav aria-label="${l.nav}" class="navlinks"><a href="${budapestPath(locale,'tours/buda-castle-ezraider-tour')}">${l.buda}</a><a href="${budapestPath(locale,'tours/margaret-island-ezraider-tour')}">${l.margaret}</a><a href="${budapestPath(locale,'tours/buda-margaret-extended-tour')}">${l.extended}</a><a href="${budapestPath(locale,'private-tours')}">${l.private}</a><a href="${ptLink}">${l.portugal}</a><a class="btn" data-personalize-cta="" data-track="booking_cta" href="${bookingHref(locale,suffix)}">${l.availability}</a><span aria-label="${l.language}" class="language-picker"><a class="lang-switch${active('en')}" href="${equivalent.en}" hreflang="en">EN</a><a class="lang-switch${active('hu')}" href="${equivalent.hu}" hreflang="hu">HU</a><a class="lang-switch${active('he')}" href="${equivalent.he}" hreflang="he">עברית</a></span></nav></div></header>`;}
function budapestFooter(locale){const l=budapestLabels(locale),manage=locale==='he'?'/manage/?lang=he':locale==='hu'?'/manage/?lang=hu':'/manage/';return`<footer><div class="wrap footergrid footergrid-v2"><div><div class="brand">VOY<span>PRO</span></div><p>${l.intro}</p><p class="small">Városház u. 14 · 1052 Budapest</p></div><div><b>${l.tours}</b><p><a href="${budapestPath(locale,'tours/buda-castle-ezraider-tour')}">${l.budaFull}</a><br/><a href="${budapestPath(locale,'tours/margaret-island-ezraider-tour')}">${l.margaretFull}</a><br/><a href="${budapestPath(locale,'tours/buda-margaret-extended-tour')}">${l.extendedFull}</a><br/><a href="${budapestPath(locale,'private-tours')}">${l.privateFull}</a><br/><a href="${budapestPath(locale,'with-kids')}">${l.kids}</a></p></div><div><b>${l.plan}</b><p><a href="${budapestPath(locale,'first-day')}">${l.first}</a><br/><a href="${budapestPath(locale,'where-to-stay')}">${l.stay}</a><br/><a href="${budapestPath(locale,'group-tours')}">${l.groups}</a><br/><a href="${budapestPath(locale,'corporate-events')}">${l.corporate}</a></p></div><div><b>${l.service}</b><p><a href="${manage}">${l.manage}</a><br/><a data-track="whatsapp_clicked" data-wa="" href="#">WhatsApp</a><br/><a href="tel:+36300993099">+36 30 099 3099</a></p></div></div></footer>`;}
const partnerUrl='https://www.pombais.pt/turismo/tour/ezrider/?utm_source=voy-pro&utm_medium=referral&utm_campaign=marvao';
function portugalLabels(locale){if(locale==='he')return{nav:'ניווט ראשי',tours:'סיורים',budapest:'בודפשט',availability:'בדיקת זמינות עם השותף המקומי',language:'שפה',intro:'חוויות EZRaider במרבאו, פורטוגל.',destinations:'יעדים',portugal:'פורטוגל · מרבאו',partner:'שותף מקומי'};if(locale==='pt')return{nav:'Navegação principal',tours:'Passeios',budapest:'Budapeste',availability:'Ver disponibilidade com o parceiro local',language:'Idioma',intro:'Experiências EZRaider em Marvão, Portugal.',destinations:'Destinos',portugal:'Portugal · Marvão',partner:'Parceiro local'};return{nav:'Primary navigation',tours:'Tours',budapest:'Budapest',availability:'Check availability with local partner',language:'Language',intro:'EZRaider experiences in Marvão, Portugal.',destinations:'Destinations',portugal:'Portugal · Marvão',partner:'Local partner'};}
function portugalHeader(locale){const l=portugalLabels(locale),home=locale==='he'?'/he/portugal/':locale==='pt'?'/pt/portugal/':'/portugal/',bud=locale==='he'?'/he/budapest/':'/budapest/',active=c=>c===locale?' active is-current':'';return`<header><div class="wrap nav"><a class="brand" href="${home}">VOY<span>PRO</span></a><nav aria-label="${l.nav}" class="navlinks"><a href="${home}#tours">${l.tours}</a><a href="${bud}">${l.budapest}</a><a class="btn" href="${partnerUrl}" rel="noopener noreferrer" target="_blank">${l.availability}</a><span aria-label="${l.language}" class="language-picker"><a class="lang-switch${active('en')}" href="/portugal/" hreflang="en">EN</a><a class="lang-switch${active('he')}" href="/he/portugal/" hreflang="he">עברית</a><a class="lang-switch${active('pt')}" href="/pt/portugal/" hreflang="pt">PT</a></span></nav></div></header>`;}
function portugalFooter(locale){const l=portugalLabels(locale),home=locale==='he'?'/he/portugal/':locale==='pt'?'/pt/portugal/':'/portugal/',bud=locale==='he'?'/he/budapest/':'/budapest/';return`<footer><div class="wrap footergrid footergrid-v2"><div><div class="brand">VOY<span>PRO</span></div><p>${l.intro}</p><p class="small">Marvão · Portalegre · Portugal</p></div><div><b>${l.destinations}</b><p><a href="${home}">${l.portugal}</a><br/><a href="${bud}">${l.budapest}</a></p></div><div><b>${l.partner}</b><p><a href="${partnerUrl}" rel="noopener noreferrer" target="_blank">Pombais Experience &amp; Villas</a></p></div></div></footer>`;}
function normalizeSharedUI(html,rel){const locale=pageLocale(rel),route=routeFromRel(rel);html=html.replace(/<html\b([^>]*)>/i,(m,attrs)=>{let next=attrs.replace(/\s+lang=["'][^"']+["']/i,'').replace(/\s+dir=["'][^"']+["']/i,'');return`<html lang="${locale}"${locale==='he'?' dir="rtl"':''}${next}>`;});html=html.replace(/<body\b([^>]*)>/i,(m,attrs)=>{let next=attrs.replace(/\s+data-page=["'][^"']+["']/i,'');if(locale==='he'&&!/class=["'][^"']*\brtl\b/i.test(next))next=next.replace(/class=["']([^"']*)["']/i,(mm,c)=>`class="rtl ${c}"`);return`<body${next} data-page="${route}">`;});if(/^(?:he\/|hu\/)?budapest\//.test(rel)){const suffix=budapestSuffix(rel);html=html.replace(/<header\b[\s\S]*?<\/header>/i,budapestHeader(locale,suffix));html=html.replace(/<footer\b[\s\S]*?<\/footer>/i,budapestFooter(locale));const generic=budapestPath(locale)+'#booking',intended=bookingHref(locale,suffix);if(intended!==generic)html=html.split(`href="${generic}"`).join(`href="${intended}"`);}else if(/^(?:he\/|pt\/)?portugal\/index\.html$/.test(rel)){html=html.replace(/<header\b[\s\S]*?<\/header>/i,portugalHeader(locale));html=html.replace(/<footer\b[\s\S]*?<\/footer>/i,portugalFooter(locale));}return html;}

for(const file of walk(dist).filter(f=>f.endsWith('.html'))){const rel=path.relative(dist,file).replaceAll('\\','/');if(rel==='manage/index.html'||rel==='404.html'||rel==='index.html')continue;let html=fs.readFileSync(file,'utf8');html=normalizeSharedUI(html,rel);fs.writeFileSync(file,html);}

const siteJs=path.join(dist,'assets','site.js');
let js=fs.readFileSync(siteJs,'utf8');
const replacements=[
 ["    hydrateCatalog();\n    form.addEventListener('change'", "    hydrateCatalog().then(()=>{\n      if(qs.get('mode')==='private'){\n        const mode=document.querySelector('[data-private-upgrade]');\n        if(mode&&typeof mode._setBookingMode==='function'&&!mode.hidden) mode._setBookingMode('private',{silent:true});\n      }\n    });\n    form.addEventListener('change'"],
 ["'No live departures found right now.':'Jelenleg nincs elérhető indulás.'", "'No departures found right now.':'Jelenleg nincs elérhető indulás.'"],
 ["t('No live departures found right now.','לא נמצאו יציאות זמינות כרגע.')", "t('No departures found right now.','לא נמצאו יציאות זמינות כרגע.')"],
 ["' · team check':' · csapatellenőrzés'", "' · confirmation':' · megerősítés'"],
 ["t(' · team check',' · נדרש אישור צוות')", "t(' · confirmation',' · נדרש אישור')"],
 ["'This booking needs support.':'Ehhez a foglaláshoz egy gyors csapatellenőrzés szükséges.'", "'This booking needs a quick confirmation.':'Ehhez a foglaláshoz gyors megerősítés szükséges.'"],
 ["t('This booking needs support.','ההזמנה הזו דורשת סיוע.')", "t('This booking neds a quick confirmation.'ההזמנה הזו דורשת אישור קצר.')"],
 ["'This group needs a quick availability check from our local team.':'Ehhez a csoporthoz egy gyors elérhetőségi ellenőrzés szükséges a helyi csapattól.'", "'This group needs a quick availability confirmation.':'Ehhez a csoporthoz gyors elérhetőségi megerősítés szükséges.'"],
 ["t('This group needs a quick availability check from our local team.','הקבוצה דורשת אישור צוות/כלי נוסף.')", "t('This group needs a quick availability confirmation.','לקבוצה הזו נדרש אישור זמינות קצר.')"],
 ["t('Request confirmation','בקשת אישור צוות')", "t('Request confirmation','בקשת אישור')"],
 ["'Availability could not be loaded. No sample times are being shown.':'Az aktuális időpontokat most nem sikerült betölteni. Írj nekünk WhatsAppon.'", "'Availability could not be loaded. Please contact us on WhatsApp.':'Az aktuális időpontokat most nem sikerült betölteni. Írj nekünk WhatsAppon.'"],
 ["t('Availability could not be loaded. No sample times are being shown.','לא הצלחנו לטעון זמינות. לא מוצגות שעות לדוגמה.')", "t('Availability could not be loaded. Please contact us on WhatsApp.','לא הצלחנו לטעון זמינות. אפשר לפנות אלינו ב‑WhatsApp.')"]
];
for(const [from,to] of replacements){if(js.includes(from))js=js.replace(from,to);}
fs.writeFileSync(siteJs,js);

const releasePath=path.join(dist,'release.json');
const release=JSON.parse(fs.readFileSync(releasePath,'utf8'));
release.version='1.32.0';
fs.writeFileSync(releasePath,JSON.stringify(release,null,2)+'\n');
console.log('Applied VOY PRO v1.32 staging stabilization overrides.');
